# -*- coding: utf-8 -*-
"""sorteioMP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19znE0dvjsu2z-YQDOD5qR4omZZP2mDUV
"""

import pandas as pd
import random

# Lê o resultado da query exportada do BigQuery
df = pd.read_csv("base_sorteio.csv")

# Garante que numeros_da_sorte seja inteiro
df["numeros_da_sorte"] = df["numeros_da_sorte"].fillna(0).astype(int)

# Cria a lista de tickets (cada escola repete conforme o número da sorte)
tickets = []
for _, row in df.iterrows():
    tickets.extend([(row["branch_id"], row["branch_name"])] * row["numeros_da_sorte"])

# Define semente (para reprodutibilidade)
random.seed(42)

# Sorteia 1 vencedor
vencedor = random.choice(tickets)
print(f"🎉 Escola vencedora:\nID: {vencedor[0]} | Nome: {vencedor[1]}")

# Sorteia vários vencedores (sem repetição)
# Aqui usamos set() pra garantir que uma mesma escola não saia repetida
vencedores = random.sample(list({v for v in tickets}), k=5)
print("\n🏆 Escolas sorteadas:")
for i, v in enumerate(vencedores, 1):
    print(f"{i}. {v[1]} (ID: {v[0]})")